version: 2
updates:
  - package-ecosystem: deno
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "Type: Maintenance"
    groups:
      fresh-preact:
        patterns:
          - "*fresh*"
          - "preact"
          - "*preact*"
      hono:
        patterns:
          - "*hono*"
      simplewebauthn:
        patterns:
          - "@simplewebauthn/*"
      deno-std:
        patterns:
          - "$std/*"
          - "@std/*"
  - package-ecosystem: docker
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "Type: Maintenance"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "Type: Maintenance"
    groups:
      actions-org:
        patterns:
          - "actions/*"
